# Generated by Django 5.1 on 2024-08-29 09:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='category_name')),
                ('desk', models.TextField(blank=True, null=True)),
                ('thumb', models.ImageField(blank=True, null=True, upload_to='photos_category/%Y/%m/%d')),
            ],
        ),
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='day_name')),
                ('desk', models.TextField()),
                ('photos', models.ImageField(blank=True, null=True, upload_to='photos_day/%Y/%m/%d')),
            ],
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Tour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='tour_name')),
                ('desc', models.TextField(blank=True, null=True)),
                ('tag', models.CharField(max_length=150, verbose_name='tags')),
                ('link', models.CharField(max_length=150, verbose_name='link')),
                ('price', models.CharField(max_length=150, verbose_name='price')),
                ('thumb', models.CharField(max_length=150, verbose_name='thumbnail')),
                ('in_and_out', models.CharField(max_length=150, verbose_name='in_and_out')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend_api.category')),
                ('days', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend_api.day')),
                ('gallery', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend_api.gallery')),
            ],
        ),
    ]
