# Generated by Django 5.1 on 2024-08-29 09:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '0002_remove_tour_category_remove_tour_days_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tour',
            name='days',
        ),
        migrations.AddField(
            model_name='tour',
            name='days',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend_api.day'),
        ),
    ]
