# Generated by Django 5.1 on 2024-08-29 10:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '0003_remove_tour_days_tour_days'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tour',
            name='days',
        ),
        migrations.AddField(
            model_name='day',
            name='tour',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='backend_api.tour'),
        ),
    ]
