# Generated by Django 5.1 on 2024-08-29 10:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '0004_remove_tour_days_day_tour'),
    ]

    operations = [
        migrations.AlterField(
            model_name='day',
            name='tour',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='days', to='backend_api.tour'),
        ),
    ]
